blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Discuss an Idea
    url: https://github.com/TuwaIO/web3-transactions-tracking/discussions
    about: Please use GitHub Discussions for questions and broader conversations.